name: AIHound - Docker Credentials - Docker configs and contents
guid: 0eeaaaca-9eee-42f0-b9b4-5b961c28d30a
prebuilt: false
platforms: 
category: AIHound
description: Docker configuration files and the credentials they contain.
query: |-
  MATCH path = (d:AIHound_DockerConfig)-[:AIHound_ContainsCredential]->(c:AIHound_AICredential)
  RETURN path
revision: 1
resources: https://github.com/netwrix/AIHound
acknowledgements: AIHound, DFIRDeferred
